name = "EquilibriumPropagation"
uuid = "5f68fc10-9f8b-4f9a-a08a-3d2f5c2d3b86"
version = "0.1.0"
authors = ["EquilibriumPropagation.jl contributors"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ADTypes = "1.22.2"
CommonSolve = "0.2.11"
DifferentiationInterface = "0.7.20"
Enzyme = "0.13"
Functors = "0.5.2"
Lux = "1.31"
NonlinearSolve = "3, 4"
Optimisers = "0.4"
OrdinaryDiffEqRosenbrock = "1, 2"
OrdinaryDiffEqTsit5 = "1, 2"
Reactant = "0.2"
SciMLBase = "2, 3"
SteadyStateDiffEq = "2"
julia = "1.10"

[weakdeps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"

[extensions]
EquilibriumPropagationLuxExt = "Lux"
EquilibriumPropagationNonlinearSolveExt = ["SciMLBase", "NonlinearSolve"]
EquilibriumPropagationOptimisersExt = "Optimisers"
EquilibriumPropagationOrdinaryDiffEqRosenbrockExt = [
    "SciMLBase",
    "OrdinaryDiffEqRosenbrock",
]
EquilibriumPropagationOrdinaryDiffEqTsit5Ext = ["SciMLBase", "OrdinaryDiffEqTsit5"]
EquilibriumPropagationReactantExt = ["Reactant", "Enzyme"]
EquilibriumPropagationReactantOptimisersExt = ["Reactant", "Enzyme", "Optimisers"]
EquilibriumPropagationSteadyStateDiffEqExt = ["SciMLBase", "SteadyStateDiffEq"]

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = [
    "ForwardDiff",
    "NonlinearSolve",
    "Optimisers",
    "OrdinaryDiffEqRosenbrock",
    "OrdinaryDiffEqTsit5",
    "Printf",
    "Random",
    "SciMLBase",
    "SteadyStateDiffEq",
    "Test",
]
